# Generated by Django 3.2.6 on 2021-09-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
