# Generated by Django 3.2.6 on 2021-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0002_auto_20210911_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
    ]
