# Generated by Django 3.2.6 on 2021-10-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0004_alter_contacts_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
